version: '3.8'

services:
  beef:
    image: beefproject/beef
    container_name: beef
    ports:
      - "8888:3000"   # UI Web (puerto 8888 externo -> 3000 interno)
      - "6789:6789"   # Hook
      - "61985:61985" # WebSocket
      - "61986:61986" # WebSocket
    volumes:
      - beef-data:/opt/beef/data
    environment:
      - BEEF_USER=beef
      - BEEF_PASSWD=MiPasswordSeguro123
    restart: unless-stopped

volumes:
  beef-data:
